file:
  - Facebook/comments/comments.json
  - Facebook/likes_and_reactions/posts_and_comments.json
  - Facebook/posts/your_posts.json
  - Facebook/posts/other_people's_posts_to_your_timeline.json
  - Facebook/search_history/your_search_history.json
keysForMerge:
  Comment: ~
  Post: ~
  Query:
    - query

sourceKeys:
  Comment:
    - targetContentAuthor
    - targetContentFbLocation
  Post:
    - targetContentAuthor
    - targetContentFbLocation
    - mentions
  Query: ~
sourceTypePerKey:
  targetContentFbLocation: "Facebook Location"
  targetContentAuthor: "Facebook Account"
  mentions: "Facebook Account"
sourceRelationship:
  targetContentFbLocation: "Placed"
  targetContentAuthor: "InherentMention"
  mentions: "InherentMention"
sourcesToIgnore:
  - Self

termsToIgnore: []
entityExtractionKeys:
  Comment: ~
  Post: ~
  Query: ~
inherentTags:
  Comment: ~
  Post: ~
  Query: ~

