file: Google/A_minha_atividade.json
keysForMerge:
  Query:
    - query
  Webpage:
    - title
sourceKeys:
  Query: ~
  Webpage:
    - url
sourceTypePerKey:
  url: URL
sourceRelationship:
  url: "Authorship"
sourcesToIgnore: []
termsToIgnore:
  - "Used Search"
entityExtractionKeys:
  Query:
    - query
  Webpage:
    - title
inherentTags:
  Query: ~
  Webpage: ~