platforms:
  Facebook: facebook.yaml
  YouTube: youtube.yaml
  GoogleSearch: googleSearch.yaml
  Reddit: reddit.yaml
  Twitter: twitter.yaml
dataDir: '../../data/'
plotDir: '../../data/Plots'
centralityDir: '../../data/Centrality'
initialPipeline:
  - processContent.py
  - entityExtraction.py
  - processTags.py
  - createGraph
analysisPipeline:
  - activityPlots.py
  - classDistributionPlots.py
  - centralityPlots   # Takes a long time