file:
  - Reddit/comments.csv
  - Reddit/posts.csv
keysForMerge:
  Comment: ~
  Post: ~
sourceKeys:
  Comment:
    - subreddit
  Post:
    - subreddit
sourceTypePerKey:
  subreddit: Subreddit
sourceRelationship:
  subreddit: "Placed"
sourcesToIgnore: []
termsToIgnore: []
entityExtractionKeys:
  Comment:
    - body
  Post:
    - title
    - body
inherentTags:
  Comment: ~
  Post: ~
