class: TwitterInterpreter
file:
  - Twitter/tweet.json
keysForMerge:
  Post: ~

sourceKeys:
  Post:
    - userMentions
sourceTypePerKey:
  userMentions: "Twitter Account"
sourceRelationship:
  userMentions: "InherentMention"
sourcesToIgnore: []

termsToIgnore: []
entityExtractionKeys:
  Post:
    - body
inherentTags:
  Post:
    - hashtags
    - symbols
