file: YouTube/A_minha_atividade.json
keysForMerge:
  Query:
    - query
  Video:
    - channel
    - title
sourceKeys:
  Query: ~
  Video:
    - channel
sourceTypePerKey:
  channel: "YouTube Channel"
sourceRelationship:
  channel: "Authorship"
sourcesToIgnore: []
termsToIgnore:
  - "a video that has been removed"
entityExtractionKeys:
  Query:
    - query
  Video:
    - title
inherentTags:
  Query: ~
  Video: ~
